
spring:
  jpa:
    # 数据库平台配置
    database-platform: org.hibernate.dialect.MySQLDialect
    # SQL显示配置
    show-sql: true
    # DDL配置
    generate-ddl: false
    # 实体扫描配置
    packages-to-scan:
      - cn.carey.jpa.entity
    # Hibernate特定配置
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
    # Repository配置
    repository:
      packages:
        - cn.carey.jpa.repository